
name: 'Dev-Branch-CI'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  DevBranchCI:
    name: 'DevBranchCI'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        run: git branch -a
