
name: 'Dev-Branch-CI'

on:
  push:
    branches: [ "ROBO-*" ]

permissions:
  contents: read

jobs:
  DevBranchCI:
    name: 'DevBranchCI'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        run: npm install

      - name: Run Test cases
        run: echo npm test

#