
name: 'PR'

on: pull_request

permissions:
  contents: read

jobs:
  PR:
    name: 'PR'
    runs-on:
      labels: self-hosted
#    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        run: npm install

      - name: Run Code Quality
        run: sonar-scanner -Dsonar.host.url=http://54.161.118.88:9000 -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=cart -Dsonar.qualitygate.wait=true  -Dsonar.exclusions=node_modules/**
        env:
          SONAR_TOKEN: ${{  secrets.SONAR_TOKEN }}

      - name: Install NodeJS Dependencies
        run: npm install

