
name: 'ReleaseTag'

on:
  push:
    tags:
      - '*'
permissions:
  contents: read

jobs:
  PR:
    name: 'ReleaseTag'
    runs-on:
      labels: self-hosted
#    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS Dependencies
        run: env

#      - name: Create Archive
#        run: |
#          echo $TAG_NAME > VERSION
#          zip -r $repo_name-$TAG_NAME.zip *'
#        env:
#          SONAR_TOKEN: ${{  secrets.SONAR_TOKEN }}
#
#      - name: Install NodeJS Dependencies
#        run: npm install

##